// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function se(prim) {
  return prim;
}

function About(Props) {
  var close = Props.close;
  return React.createElement("div", {
              className: "About",
              onClick: close
            }, React.createElement("div", {
                  className: "About-content",
                  onClick: (function (prim) {
                      prim.stopPropagation();
                      
                    })
                }, React.createElement("p", undefined, "Si is an online version of ", React.createElement("a", {
                          href: "https://en.wikipedia.org/wiki/Score_Four",
                          target: "_blank"
                        }, "Score Four"), ", or 3D ", React.createElement("a", {
                          href: "https://en.wikipedia.org/wiki/Connect_Four",
                          target: "_blank"
                        }, "Connect Four"), ". ", "The name, Si, means four in Chinese — 四 / 肆."), React.createElement("p", undefined, "The rule is simple: two players take turns to put pieces on one of the 16 columns, with the objective of connecting 4 of your pieces in a straight line in any direction."), React.createElement("p", undefined, "In its current form, two players play on the same computer. Future versions may introduce remote games, and AI players."), React.createElement("p", undefined, React.createElement("i", undefined, "Made by ", React.createElement("a", {
                              href: "http://scottcheng.com",
                              target: "_blank"
                            }, "Scott Cheng"), ". ", "Written in ", React.createElement("a", {
                              href: "https://reasonml.github.io/",
                              target: "_blank"
                            }, "Reason"), " and open sourced on ", React.createElement("a", {
                              href: "https://github.com/scottcheng/si-reason",
                              target: "_blank"
                            }, "GitHub"), "."))));
}

var make = About;

export {
  se ,
  make ,
  
}
/* react Not a pure module */
