// Generated by ReScript, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as $$Array from "bs-platform/lib/es6/array.js";
import * as React from "react";
import * as Util$SiReason from "../util.bs.js";
import * as Board$SiReason from "../board.bs.js";

function columnKey(x, y) {
  return "" + x + "-" + y;
}

function markerId(x, y) {
  return "BoardBase-marker-" + x + "-" + y;
}

function position(x) {
  return ((0.125 + (1.0 - 0.125 * 2.0) / (Board$SiReason.numRows - 1 | 0) * x) * 100.0).toString() + "%";
}

function baseTransform(rotation, winning) {
  return "translate3d(-50%, -50%, -10000px) rotateX(62deg) rotateZ(" + (String((rotation + 16 | 0) + (
                winning ? 3600 : 0
              ) | 0) + "deg)");
}

function BoardBase(Props) {
  var rotation = Props.rotation;
  var winning = Props.winning;
  return React.createElement("div", {
              className: Util$SiReason.cx({
                    hd: [
                      "BoardBase",
                      true
                    ],
                    tl: {
                      hd: [
                        "BoardBase--winning",
                        winning
                      ],
                      tl: /* [] */0
                    }
                  }),
              style: {
                transform: baseTransform(rotation, winning)
              }
            }, $$Array.of_list(List.map((function (param) {
                        var y = param[1];
                        var x = param[0];
                        return React.createElement("div", {
                                    key: columnKey(x, y),
                                    className: "BoardBase-mark",
                                    id: markerId(x, y),
                                    style: {
                                      left: position(y),
                                      position: "absolute",
                                      top: position(x)
                                    }
                                  });
                      }), Board$SiReason.ijList)));
}

var boardPadding = 0.125;

var make = BoardBase;

export {
  columnKey ,
  markerId ,
  boardPadding ,
  position ,
  baseTransform ,
  make ,
  
}
/* react Not a pure module */
