// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Game$SiReason from "./Game.bs.js";

function Si(Props) {
  return React.createElement("div", {
              className: "Si"
            }, React.createElement(Game$SiReason.make, {}));
}

var make = Si;

export {
  make ,
  
}
/* react Not a pure module */
