// Generated by ReScript, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as $$Array from "bs-platform/lib/es6/array.js";
import * as React from "react";
import * as Util$SiReason from "../util.bs.js";
import * as Board$SiReason from "../board.bs.js";

function se(prim) {
  return prim;
}

function Sidebar(Props) {
  var gameState = Props.gameState;
  var rotateClockwise = Props.rotateClockwise;
  var rotateCounterClockwise = Props.rotateCounterClockwise;
  var reset = Props.reset;
  var openAbout = Props.openAbout;
  return React.createElement("div", {
              className: "Sidebar"
            }, React.createElement("div", {
                  className: "Sidebar-title"
                }, "SI"), React.createElement("div", {
                  className: "Sidebar-section"
                }, $$Array.of_list(List.mapi((function (i, param) {
                            var player = param[0];
                            var match = Board$SiReason.winner(gameState.board);
                            return React.createElement("div", {
                                        key: String(i),
                                        className: Util$SiReason.cx({
                                              hd: [
                                                "Sidebar-subSection",
                                                true
                                              ],
                                              tl: {
                                                hd: [
                                                  "Sidebar-player",
                                                  true
                                                ],
                                                tl: {
                                                  hd: [
                                                    "Sidebar-player--active",
                                                    gameState.player === player
                                                  ],
                                                  tl: {
                                                    hd: [
                                                      "Sidebar-player--winner",
                                                      match !== undefined ? match[0] === player : false
                                                    ],
                                                    tl: /* [] */0
                                                  }
                                                }
                                              }
                                            })
                                      }, React.createElement("div", {
                                            className: player ? "Sidebar-playerBead Sidebar-playerBead--p2" : "Sidebar-playerBead Sidebar-playerBead--p1"
                                          }), param[1]);
                          }), {
                          hd: [
                            /* P1 */0,
                            "Player 1"
                          ],
                          tl: {
                            hd: [
                              /* P2 */1,
                              "Player 2"
                            ],
                            tl: /* [] */0
                          }
                        }))), React.createElement("div", {
                  className: "Sidebar-section"
                }, React.createElement("div", {
                      className: "Sidebar-rotateBtn icon-rotate-left",
                      onClick: rotateClockwise
                    }), React.createElement("div", {
                      className: "Sidebar-rotateBtn icon-rotate-right",
                      onClick: rotateCounterClockwise
                    })), React.createElement("div", {
                  className: "Sidebar-info"
                }, React.createElement("div", {
                      className: "Sidebar-subSection"
                    }, React.createElement("span", {
                          className: "Sidebar-link",
                          onClick: reset
                        }, "New game")), React.createElement("div", {
                      className: "Sidebar-subSection"
                    }, React.createElement("span", {
                          className: "Sidebar-link",
                          onClick: openAbout
                        }, "About"))));
}

var make = Sidebar;

export {
  se ,
  make ,
  
}
/* react Not a pure module */
