// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Board$SiReason from "./board.bs.js";

var initialState = {
  board: Board$SiReason.emptyState,
  player: /* P1 */0
};

function otherPlayer(player) {
  if (player) {
    return /* P1 */0;
  } else {
    return /* P2 */1;
  }
}

function move(param, param$1) {
  var player = param$1.player;
  var board = param$1.board;
  var y = param[1];
  var x = param[0];
  if (Board$SiReason.isValidMove([
          x,
          y
        ], board)) {
    return {
            board: Board$SiReason.move([
                  x,
                  y
                ], player, board),
            player: player ? /* P1 */0 : /* P2 */1
          };
  } else {
    return {
            board: board,
            player: player
          };
  }
}

export {
  initialState ,
  otherPlayer ,
  move ,
  
}
/* Board-SiReason Not a pure module */
