// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as Si$SiReason from "./components/Si.bs.js";

import './main.scss'
;

var root = document.querySelector("#root");

if (root == null) {
  console.log("Coudn't find #root element to mount the React app.");
} else {
  ReactDom.render(React.createElement(Si$SiReason.make, {}), root);
}

export {
  
}
/*  Not a pure module */
